# Общие сообщения плагина
messages:
  on-place:
    enabled: true
    text: "&e[{type}] заряд активирован! Радиус: {radius}"

settings:
  region-checks:
    enabled: true
    mode: STRICT
    deny-message: "&cЗдесь нельзя подрывать."

version: 2

defaults:
  primed:
    fuse-ticks: 60
  behavior:
    ignite-when-placed: true
    break-blocks: true
    api-only: false
    drop-blocks: false
    whitelist-only: false
    whitelist: []
    blacklist: [BEDROCK]
    max-blocks: -1

mixins:
  radius15:
    behavior:
      radius: 15.0

  underwater:
    primed:
      explode-in-water: true
    behavior:
      allow-fluids: true

  obsidian_breaker:
    behavior:
      allow-obsidian: true
      allow-crying-obsidian: true

  no_drops:
    behavior:
      drop-blocks: false

  drops:
    behavior:
      drop-blocks: true

  whitelist_obsidian_only:
    behavior:
      whitelist-only: true
      whitelist: [OBSIDIAN, CRYING_OBSIDIAN]

types:
  tire_white_base:
    item:
      material: TNT
      display-name: "&f&lTire White &7[TNT]"
      lore:
        - "&7Базовый каст-TNT"
      persistent-data:
        variant: tire_white
    primed:
      custom-name: "&f&lTire White"
      show-name: false
    behavior: {}

  tire_white:
    extends: tire_white_base
    use: [radius15, no_drops]

  tire_black:
    extends: tire_white_base
    use: [radius15, obsidian_breaker, no_drops]

  tire_hydro_black:
    extends: tire_black
    use: [underwater]

merge:
  lists: "append-dedupe"
  maps: "deep"
