name: CustomTNTFlow
main: dev.byflow.customtntflow.CustomTNTFlowPlugin
version: 1.1.0
author: ChatGPT
description: Highly configurable custom TNT types with API integration for region damage plugins.
api-version: '1.20'
commands:
  tntflow:
    description: Custom TNTFlow administration command
    usage: "/<command> reload"
    permission: customtntflow.admin
permissions:
  customtntflow.admin:
    description: Allows administrating CustomTNTFlow features
    default: op
